// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyqpgwsiuvzqdxwghsat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5cXBnd3NpdXZ6cWR4d2doc2F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODY0NzAsImV4cCI6MjA2OTI2MjQ3MH0.4MoWUHfFc14v4J76DVKArlKWr93dWN6V-uclqZWlPMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});